### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by shaman-narayanasamy** [simroux/VirSorter#1]
Dear authors,

Is this tool available as a stand alone? I am trying to run it on the iPlant platform, but it says the tool is unavailable.

**Comment by simroux** [comment]
Dear Shaman,

Unfortunately, VirSorter on iPlant is indeed unavailable for now, we are actively working on solving this issue. You can download the source code here, however you will also need to install the different dependencies (blast, hmmsearch, metagene annotator), and download the different databases (the ones specific of VirSorter are available on iPlant : /iplant/home/shared/imicrobe/VirSorter/Database, and VirSorter also required PFAM_27).

**Comment by simroux** [comment]
Dear Shaman, 

VirSorter is back live on iPlant, and a new version adapted for Docker (https://www.docker.com) is available on this github repository, which should make the install of VirSorter as a stand-alone tool on a linux-base cluster easier.

**Comment by shaman-narayanasamy** [comment]
Hi Sim,

Thanks for the update. The instructions is slightly incorrect:

I tried:
```
$ docker pull discoenv/virsorter
Pulling repository discoenv/virsorter
Tag latest not found in repository discoenv/virsorter
```

I then tried this:
```
$ docker pull discoenv/virsorter:v1.0.3
```

I guess docker looks for the "latest" tag by default.

Best,
Shaman

**Comment by simroux** [comment]
Hi Shaman,

You're right, I forgot about this, I'll modify the instruction now. Hope  
that VirSorter will work on your side now !

Best,

Simon
