### ISSUE TITLE
errors from dockerhub virsoter

### ISSUE THREAD

**Issue by DanieleDeco** [simroux/VirSorter#12]
Hey,

I am trying to run my virome with VirSoter on my machine and I got few errors.
Could you please take a look?

Many Thanks in advance.

Cheers
Daniele 

Run:
 docker run -v /Users/daniele1/Desktop/VirSorter/virsorter-data:/data -v /Users/daniele1/Desktop/VirSorter/virsorter-run:/wdir -w /wdir --rm discoenv/virsorter:v1.0.3 --db 2 --fna /wdir/input_contig.fna

Cleaning the output directory
rm -r r_0/db : 
mv: cannot stat 'Contigs_prots_vs_PFAMa.tab': No such file or directory
mv: cannot stat 'Contigs_prots_vs_PFAMa.out': No such file or directory
mv: cannot stat 'Contigs_prots_vs_PFAMb.tab': No such file or directory
mv: cannot stat 'Contigs_prots_vs_PFAMb.out': No such file or directory
mv: cannot stat 'error.log': No such file or directory
mv: cannot stat 'formatdb.log': No such file or directory
mv: cannot stat 'VIRSorter_affi-contigs.csv': No such file or directory
mv: cannot stat 'VIRSorter_affi-contigs.refs': No such file or directory
mv: cannot stat 'VIRSorter_phage-signal.csv': No such file or directory

The log file:

Error: Failed to open sequence file /wdir/fasta/VIRSorter_prots.fasta for reading

Error: Failed to open sequence file /wdir/fasta/VIRSorter_prots.fasta for reading

Error: Failed to open sequence file /wdir/fasta/VIRSorter_prots.fasta for reading

[blastall] FATAL ERROR: blast: Unable to open input file /wdir/fasta/VIRSorter_prots.fasta

Can't open '/wdir/fasta/VIRSorter_circu.list' for reading: 'No such file or directory' at /usr/local/bin/Scripts/Step_2_merge_contigs_annotation.pl line 39
Can't open 'VIRSorter_affi-contigs.csv' for reading: 'No such file or directory' at /usr/local/bin/Scripts/Step_3_highlight_phage_signal.pl line 43
Can't open 'VIRSorter_phage-signal.csv' for reading: 'No such file or directory' at /usr/local/bin/Scripts/Step_4_summarize_phage_signal.pl line 83

**Comment by DanieleDeco** [comment]
I randomly get this one as well.

Can't open '/wdir/input_contig.fna' for reading: 'No such file or directory' at /usr/local/bin/wrapper_phage_contigs_sorter_iPlant.pl line 148

**Comment by simroux** [comment]
Hi Daniele,

This looks like VirSorter having troubles reading your input files and/or writing in the working directory. Could there be some permission issues in /Users/daniele1/Desktop/VirSorter/virsorter-run ? Also, could you post here the content of /Users/daniele1/Desktop/VirSorter/virsorter-run and /Users/daniele1/Desktop/VirSorter/virsorter-run/fasta (or /Users/daniele1/Desktop/VirSorter/virsorter-run/Fasta_files/) after one of these failed runs ?

**Comment by DanieleDeco** [comment]
Hi Simon,

I solved the problem, I had to change the directory permission.

Many Thanks for your help.

Cheers
Daniele

**Comment by simroux** [comment]
Great, happy that it's solved !
