### ISSUE TITLE
Is it possible to extract all sequences that are circular? Not just those which fall into a category?

### ISSUE THREAD

**Issue by feargalr** [simroux/VirSorter#13]
Basically I want to use being circular as a criteria for considering something as being a potentially viral contig as well if it passes virsorter decontamination mode. Perhaps is there info in one of the intermediate files or is it possible to just run that circular detection?

**Comment by simroux** [comment]
There is no easy way to just run the circular detection, but all circular sequences are identified with a "-circular" suffix, and the directory "Fasta_files" should have a file "VirSorter_circu.list" which lists all of the contigs identified as circular.

Let me know if any of this would work for what you are trying to do !

**Comment by feargalr** [comment]
Thanks. Just to clarify does this list include those that would fail other criteria and thus wouldn't be categorized into 1 - 6 in VIRSorter_global-phage-signal.csv?

**Comment by simroux** [comment]
Yes, this list is generated before any of the viral detection is started.

**Comment by feargalr** [comment]
Perfect. This is exactly what I wanted. Thanks for your help
