### ISSUE TITLE
How to download the database? 

### ISSUE THREAD

**Issue by jolespin** [simroux/VirSorter#15]
![image](https://user-images.githubusercontent.com/9061708/30391941-1317ee0e-9870-11e7-8310-640dce99abc8.png)

The link to the download instructions brought me back to this for a full circle.  Is there any way I can just use `wget` instead of installing software to download the data?  Do you guys have the 4 GB dataset on Google Drive or any FTP site?

**Comment by simroux** [comment]
If not through Cyverse, the easiest way to download the database is probably via using the Docker version of VirSorter (https://github.com/simroux/VirSorter#docker---from-dockerhub).
Otherwise, if neither of these solutions are working, you can also grab the tar.gz from google drive: https://drive.google.com/file/d/0B6Tg-jjiojemNF9vMEFfYkl5S2s/view?usp=sharing.

Best,

Simon

**Comment by jolespin** [comment]
That Google Drive link is exactly what I was looking for!  Thank you!  Looking forward to using your tool.  I have this weird draft genome bin that looks viral from some of the annotations.

**Comment by simroux** [comment]
Sounds good, let me know if you have any issue or any question (always looking out for weird new viruses :-) )

**Comment by jolespin** [comment]
Quick question, when running: 

Where are the virsorter-run files?  I got docker install and want to deploy the image.  Thanks!
```bash
docker run -v /Applications/VirSorter/virsorter-data:/data -v /host/path/to/virsorter-run:/wdir -w /wdir --rm discoenv/virsorter:v1.0.3 --db 2 --fna /wdir/Input_contigs.fna
```

**Comment by simroux** [comment]
I did not manage the docker part so not 100% sure, but my feeling was that you don't have to put any file in host/path/to/virsorter-run, this is just a path to a folder you'll create on your machine (that you can change however you want) for VirSorter to work in.

**Comment by hjdong** [comment]
> If not through Cyverse, the easiest way to download the database is probably via using the Docker version of VirSorter (https://github.com/simroux/VirSorter#docker---from-dockerhub).
> Otherwise, if neither of these solutions are working, you can also grab the tar.gz from google drive: https://drive.google.com/file/d/0B6Tg-jjiojemNF9vMEFfYkl5S2s/view?usp=sharing.
> 
> Best,
> 
> Simon



> If not through Cyverse, the easiest way to download the database is probably via using the Docker version of VirSorter (https://github.com/simroux/VirSorter#docker---from-dockerhub).
> Otherwise, if neither of these solutions are working, you can also grab the tar.gz from google drive: https://drive.google.com/file/d/0B6Tg-jjiojemNF9vMEFfYkl5S2s/view?usp=sharing.
> 
> Best,
> 
> Simon

The link seems to have expired,could you provide it again ？Thank you.

**Comment by simroux** [comment]
The database is now available via wget:
wget https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz

**Comment by JiqiuWu** [comment]
Hi Simon,

Have you updated the database? How many PCs are included in the database now?

Many thanks,
Jiqiu

**Comment by simroux** [comment]
No update of the database recently, mostly because we have been working on VirSorter 2 :-) https://github.com/jiarong/VirSorter2

**Comment by JiqiuWu** [comment]
> No update of the database recently, mostly because we have been working on VirSorter 2 :-) https://github.com/jiarong/VirSorter2

WOOOW! COOL!
But if we use this tool, how to cite it?

Many thanks,
Jiqiu

**Comment by simroux** [comment]
The paper should be on bioRxiv relatively soon, but in the meantime you can provide the link to the github repo.
