### ISSUE TITLE
Cannot run docker image for VirSorter (docker: Error response from daemon: Mounts denied:)

### ISSUE THREAD

**Issue by jolespin** [simroux/VirSorter#16]
Are there any step-by-step directions to get this up and running? I've never used a docker before.  I can also install each of those packages and set up symbolic links if necessary.  I have the data ready to go but can't figure out how to run `VirSorter.` 

### virsorter-data
`/Applications/VirSorter/virsorter-data/`
![image](https://user-images.githubusercontent.com/9061708/30555970-1bfd1142-9c5e-11e7-8c59-266b127de85a.png)

### Input Fasta
`/Users/jespinoz/Viral/iter5__bin_34.fa`

```bash
jespinozlt-osx:Viral jespinoz$ docker pull discoenv/virsorter:v1.0.3
v1.0.3: Pulling from discoenv/virsorter
7ccc78f8af6d: Already exists
a3ed95caeb02: Already exists
fc159b297d00: Already exists
ab2379c3299b: Already exists
2f74b287b011: Already exists
198339110edc: Already exists
8e438e92597e: Already exists
805903dd3399: Already exists
4e650a49b37b: Already exists
8d688621ce05: Already exists
e1f20323421e: Already exists
45535f86a2c5: Already exists
37797ac35b59: Already exists
37b655e6666e: Already exists
357d5747771f: Already exists
b030a34166a7: Already exists
Digest: sha256:02c0acb6176ecc3f0faa984d3506c529323e0c1e5a62a90b63f826dcf97b5101
Status: Image is up to date for discoenv/virsorter:v1.0.3
jespinozlt-osx:Viral jespinoz$ docker run -v /Applications/VirSorter/virsorter-data:/data -v /Users/jespinoz/Viral/:/wdir -w /wdir --rm discoenv/virsorter:v1.0.3 --db 2 --fna /wdir/iter5__bin_34.fa
docker: Error response from daemon: Mounts denied:
The path /Applications/VirSorter/virsorter-data
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled
```

**Comment by simroux** [comment]
We don't have any VirSorter-specific step-by-step instruction for running the docker container, although if you did not use docker before, you may want to try the simpler examples in the docker tutorial (https://docs.docker.com/docker-for-mac/) to make sure everything works before running VirSorter.

Alternatively, VirSorter is also available on CyVerse, where you simply have to upload your data (in a private space) and then click a button to run the tool.
