### ISSUE TITLE
VirSorter on Docker

### ISSUE THREAD

**Issue by shaman-narayanasamy** [simroux/VirSorter#2]
Hi,

I am trying to install the docker container (both for data and the source code). First, I am trying to obtain the container with data, as per the commands provided in the README but receive an error:

```
$ docker create --name virsorter-data kyclark/virsorter-data /bin/true
Unable to find image 'kyclark/virsorter-data:latest' locally
Pulling repository kyclark/virsorter-data
Error: image kyclark/virsorter-data:latest not found
```

I tried the command to build the container anyway and received the following error...

```
$ docker build -t kyclark/virsorter-data .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM perl:latest
 ---> 5d6203dfa61c
Step 1 : MAINTAINER Ken Youens-Clark <kyclark@email.arizona.edu>
 ---> Using cache
 ---> fb525753b04f
Step 2 : COPY Generic_ref_file.refs /data/
Generic_ref_file.refs: no such file or directory
```
Is there something I am doing wrong with the commands..?

Best,
Shaman

**Comment by simroux** [comment]
Hi Shaman,

VirSorter is now available on dockerhub (https://hub.docker.com/r/discoenv/virsorter/), a new section on the readme explains how to use this version of VirSorter which does not need you to build the virsorter-data container.

Best,

Simon
