### ISSUE TITLE
SUP05_SAGs_with_viruses.fna not available on cyverse

### ISSUE THREAD

**Issue by EricDeveaud** [simroux/VirSorter#20]
Hello, 

Dockerfile for data generation uses a file that is not available on cyverse

```
COPY SUP05_SAGs_with_viruses.fna /data/
```
this file SUP05_SAGs_with_viruses.fna is not available over 

http://datacommons.cyverse.org/browse/iplant/home/shared/imicrobe/VirSorter/Data_package

regards

Eric

**Comment by simroux** [comment]
Hi Eric,
This file is not required, so you can safely drop this line from the virsorter-data Dockerfile (I just fixed the readme). Thanks for reporting !
Best,
Simon
