### ISSUE TITLE
Unable to download virsorter-data.tar.gz from Cyverse DE

### ISSUE THREAD

**Issue by blue-moon22** [simroux/VirSorter#21]
Hi there,

I am unable to download virsorter-data.tar.gz from the Discovery Environment. It downloads 1 Gb then stops with a Network Error. Same thing happens with different browsers, incognito mode and different networks.

I know this could be out of your control, but have you got any suggestions? Wouldn't want to be hampered by downloading problems.

Thanks!

**Comment by simroux** [comment]
Hi,
CyVerse recommends using Cyberduck to download large files from their system (https://pods.iplantcollaborative.org/wiki/display/DS/Using+Cyberduck+for+Uploading+and+Downloading+to+the+Data+Store). If it still fails, feel free to ask the CyVerse staff at http://ask.iplantcollaborative.org/questions/ and they should help you ge the file.

Best,
Simon

**Comment by blue-moon22** [comment]
Hi Simon,
I used duck for Linux and it works (but very slow!)
Thanks
Vicky
