### ISSUE TITLE
Bug in Step_3 is freezing the script

### ISSUE THREAD

**Issue by brymerr921** [simroux/VirSorter#23]
Hi,

I was running VirSorter (Refseq + viromes) on a metagenome assembly and noticed that it kept stopping somewhere in the middle of step 3.

The "out" log file displayed the last few lines as:
```
VIRSorter_NODE_2777_length_16061_cov_25_8054-gene_1-gene_22	22	2	gene_3-gene_18:4.46362121287209,	9.95372776823722			
VIRSorter_NODE_2784_length_16033_cov_2_92446-gene_1-gene_22	22	0	gene_5-gene_22:3.46339599606537,	gene_3-gene_22:8.87074875364101,			
Gene VIRSorter_NODE_2785_length_16032_cov_12_6685 / gene_18 -> category 0 -> putative hallmark
This is a prophage
We have a complete prophage -- we add it VIRSorter_NODE_2790_length_15982_cov_5_78584-gene_1-gene_13 !
```

I looked in Step_3 for "We have a complete prophage" and at line 408 it says just `<STDIN>;`. It seems that when certain contigs enter this section of code, it gets stuck at <STDIN>. I commented out line 408 and VirSorter proceeded to completion. I'm not sure what the purpose of this line is, or the implications are of commenting it out. If you could take a look at this, that would be great.

Best,
Bryan

**Comment by simroux** [comment]
Bug fixed in latest release, thanks Bryan for reporting it !
