### ISSUE TITLE
conda recipe yeilds perl-file-which=5.22, with perl=5.26

### ISSUE THREAD

**Issue by kgh03** [simroux/VirSorter#25]
following the conda recipe, i get perl version 5.26 but File:Which gets put into  5.22 and are not found in the @INC path.

i was able to fix this with cpan.

(virsorter) kelly@mason ~ $ wrapper_phage_contigs_sorter_iPlant.pl -f assembly.fasta --db 1 --wdir output_directory --ncpu 4 --data-dir /scratch/virsorter-data/
Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /usr/local/miniconda3/envs/virsorter/lib/site_perl/5.26.0/x86_64-linux-thread-multi /usr/local/miniconda3/envs/virsorter/lib/site_perl/5.26.0 /usr/local/miniconda3/envs/virsorter/lib/5.26.0/x86_64-linux-thread-multi /usr/local/miniconda3/envs/virsorter/lib/5.26.0 .) at /usr/local/miniconda3/envs/virsorter/bin/wrapper_phage_contigs_sorter_iPlant.pl line 47.
BEGIN failed--compilation aborted at /usr/local/miniconda3/envs/virsorter/bin/wrapper_phage_contigs_sorter_iPlant.pl line 47.

(virsorter) kelly@mason ~ $ which perl
/usr/local/miniconda3/envs/virsorter/bin/perl

(virsorter) kelly@mason ~ $ perl -v
This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-thread-multi

(virsorter) root@mason ~ $ cpan install FIle:Which

**Comment by simroux** [comment]
Hi,
If I understood correctly, you were able to successfully run VirSorter after installing File::Which separately from CPAN ? If so, thanks for reporting both the issue and the fix ! I will close this but make a link from the readme in case others have a similar problem.
