### ISSUE TITLE
No phage signal in output VIRsorter

### ISSUE THREAD

**Issue by miasungeunlee** [simroux/VirSorter#26]
#Dear Roux, 
I'm currently working on soil viruses and i got illumina metagenomic data from my soil samples (DNA-SIP data). The number of obtained reads is quite good (around 200, 000 - 600, 000 reads after quality filtering). 
I used firstly Diamond (Blastx using viral protein database uploaded from NCBI) to see if the sequences contain the viral sequences. And i found the sequences matched with some viruses. 
However, when i used the Virsorter (on Cyverse with ID: mia), there was no phage signal in output VIRsorter file (/iplant/home/mia/analyses/M54_20180228-2018-02-28-14-08-00.0). 
In Cyverse, there was no error message which means the Virsorter worked well? 
Do you think what is a problem ?? 

I tried to run also on my computer, there was an error message : 
Cannot find mga_linux_ia64
Error: Failed to open sequence file /Users/leesungeun/Desktop/Output_virsorter/fasta/VIRSorter_prots.fasta for reading
Error: Failed to open sequence file /Users/leesungeun/Desktop/Output_virsorter/fasta/VIRSorter_prots.fasta for reading
Error: Failed to open sequence file /Users/leesungeun/Desktop/Output_virsorter/fasta/VIRSorter_prots.fasta for reading
Command line argument error: Argument "query". File is not accessible:  `/Users/leesungeun/Desktop/Output_virsorter/fasta/VIRSorter_prots.fasta'
Can't open '/Users/leesungeun/Desktop/Output_virsorter/fasta/VIRSorter_circu.list' for reading: 'No such file or directory' at /Users/leesungeun/miniconda/envs/virsorter/bin/Scripts/Step_2_merge_contigs_annotation.pl line 39
Can't open '/Users/leesungeun/Desktop/Output_virsorter/VIRSorter_affi-contigs.csv' for reading: 'No such file or directory' at /Users/leesungeun/miniconda/envs/virsorter/bin/Scripts/Step_3_highlight_phage_signal.pl line 48
Can't open '/Users/leesungeun/Desktop/Output_virsorter/VIRSorter_phage-signal.csv' for reading: 'No such file or directory' at /Users/leesungeun/miniconda/envs/virsorter/bin/Scripts/Step_4_summarize_phage_signal.pl line 83

Your help is really appreciated :)
Best wishes
LEE

**Comment by simroux** [comment]
Dear Lee,

You mention a tblastx on your reads, did you assemble these reads into contigs before running VirSorter ? VirSorter is unfortunately not able to process reads, and can only work with larger contigs (ideally 10kb and more).

**Comment by miasungeunlee** [comment]
Thanks a lot for your reply :)
I didn't use assembled reads. I'll try again with the contigs. 
It seems when i assembled my reads (from Miseq V3 2*300 bp) into contigs by SPAdes, i got the contig size less than 10kb... But i'll try again :) 

Thanks
