### ISSUE TITLE
cat: r_0/Contigs_prots_vs_New_clusters.tab: No such file or directory

### ISSUE THREAD

**Issue by chadsmith123** [simroux/VirSorter#27]
Hello! I trying to run the program on Docker but . Attached is the directory of the run. Included is 'virsorter.log' which captures the screen output, including the command I executed. 

Interestingly r_0/Contigs_prots_vs_New_clusters.tab exists at the end of the run.

Thank you for your time!
[virsorter.tar.gz](https://github.com/simroux/VirSorter/files/1862069/virsorter.tar.gz)

**Comment by simroux** [comment]
Hi,
It looks like there is an issue is with the HMMER searches, you can see in the error log (logs/Virsorter_stderr_log): "Error: Unrecognized format, trying to open hmm file /data/PFAM_27/Pfam-A.hmm for reading.".

Could you double-check that you have all the correct files from the virsorter-data package ?

**Comment by chadsmith123** [comment]
Thanks for your quick reply. I took the data files from

https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz

The file is present in the working directory.
[chads@ip-172-31-2-81 virsorter]$ ls -l /home/chads/phage/virsorter/virsorter-data/PFAM_27/Pfam-A.hmm
-rw-r--r-- 1 chads chads 1.2G Feb  6 23:15 /home/chads/phage/virsorter/virsorter-data/PFAM_27/Pfam-A.hmm

**Comment by simroux** [comment]
So what might happen is a version conflict between hmmsearch in docker and the files from this new data package. Did you try with the data package recommended for Docker: http://mirrors.iplantcollaborative.org/browse/iplant/home/shared/imicrobe/VirSorter/virsorter-data.tar.gz ?

**Comment by chadsmith123** [comment]
I tried this three times in Firefox and the download stopped at exactly 1.1GB. Is it available at another location (preferable via wget)?

**Comment by simroux** [comment]
Unfortunately no, the only way I know to download these big files from CyVerse is using iCommands (https://pods.iplantcollaborative.org/wiki/display/DS/Setting+Up+iCommands). In the meantime, I will also try on my side to see if this is indeed a version conflict, and if so we may be able to release a new dockerfile.

**Comment by chadsmith123** [comment]
I tried iCommand but got:

(virsorter) [chads@ip-172-31-2-81 ~]$ iget http://mirrors.iplantcollaborative.org/browse/iplant/home/shared/imicrobe/VirSorter/virsorter-data.tar.gz
ERROR: resolveRodsTarget: srcPath /iplant/home/smith_cc/http:/mirrors.iplantcollaborative.org/browse/iplant/home/shared/imicrobe/VirSorter/virsorter-data.tar.gz does not exist
ERROR: getUtil: resolveRodsTarget status = -317000 USER_INPUT_PATH_ERR
(virsorter) [chads@ip-172-31-2-81 ~]$

**Comment by simroux** [comment]
I just released a new version of the Docker container, which now run VirSorter v1.0.5 (so will work with the data package available at https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz). 
Instructions are in the readme (but very similar to the previous docker image), let me know if that helps you run VirSorter successfully !

**Comment by chadsmith123** [comment]
Terrific. I will test it the week of April 8th.

[cid:image001.jpg@01D1AAC1.6FA947B0]<http://assemblybio.com/>

Chad C. Smith, Ph.D.

Senior Scientist I

Assembly Biosciences

csmith@assemblybio.com<mailto:csmith@assemblybio.com>

(415) 316-0861 (office)
(512) 954-2219 (cell)

**Comment by chadsmith123** [comment]
VirSorter v1.0.5 is producing output. The logs/err file is empty.
