### ISSUE TITLE
VirSorter: empty "VIRSorter_global-phage-signal.csv" and files in "Predicted_viral_sequences" have 0 size

### ISSUE THREAD

**Issue by Sapsanas** [simroux/VirSorter#29]
Hi!

I have VirSorter installed using conda, it seems to be installed correctly (it is running and creating all output files), however, all output files are empty: VIRSorter_global-phage-signal.csv and files in "Predicted_viral_sequences". 

Example of the command: 

`wrapper_phage_contigs_sorter_iPlant.pl -f ./metaSPAdes/contigs.fasta --db 1 --wdir ./VirSorter --ncpu 8 --data-dir /path/to/virsorter-data` 

I tried it on three different metagenomic contig assemblies, in all three viruses were detected by other tools (Metaphlan and VirusSeeker). 

Have you ever met this problem? Are there any solutions? 

Thank you in advance!

**Comment by simroux** [comment]
Hi ! Empty output files actually suggests that VirSorter was not installed successfully. Could you share the output folder as a zip file on this thread ? Then we could look into which steps seems to be causing the issue.

Thanks,
Best,
Simon

**Comment by Sapsanas** [comment]
Thank you for your response. 

Please, find attached the archive with VirSorter output. 
[VirSorter.zip](https://github.com/simroux/VirSorter/files/2038903/VirSorter.zip)
