### ISSUE TITLE
Error in Sliding_windows_3

### ISSUE THREAD

**Issue by jordangumm** [simroux/VirSorter#32]
I've tried multiple different parameter choices and rebuild my conda environment a few times, but I can't seem to fix an issue with the Sliding_windows_3 script.  It doesn't matter if it's in virome (decontamination) mode or not, whether or not I set '--no_c', or if I set 'diamond', etc.

Error:
*** Error in `<path>/VirSorter/Scripts/Sliding_windows_3': realloc(): invalid pointer: 0x00007fffb8a3d110 ***

I'm currently still investigating this issue, but any help would be highly appreciated.  Perhaps this is an error that has been seen before?  I noticed that the diamond version may have been a problem in [another issue](https://github.com/simroux/VirSorter/issues/28), but that resulted in a different error message.

**Comment by simroux** [comment]
Hi,

It looks like the issue for which the option "--no_c" had been implemented. This option should not call Sliding_windows_3, so I'm surprised you get an error referring to this script even when running VirSorter with "--no_c". Could you share the whole log_out file ? And, when using "--no_c", do you get the message at start-up "This is a 'no_c' run, so the C program in Step_3 will not be used and instead everything will be done in perl" as expected ?

**Comment by jordangumm** [comment]
I wasn't getting the "--no_c" message!  Actually, I was getting:

> Unknown option: no_c

Come to find out the version I was using was installed just before your June commit that added this option.  Thanks for the help in figuring this out.
