### ISSUE TITLE
mga is not detected on OSX

### ISSUE THREAD

**Issue by simone-pignotti** [simroux/VirSorter#36]
Hi,

Thanks for developing and maintaining this efficient pipeline.
I am testing the program on a mac, and I have found an issue with the MetaGeneAnnotator command.

I guess you are not supporting OSX, but I found out that a very little modification seems to do the job (I managed to run the entire pipeline and it produces the desired output).

In these two locations you use `which mga_linux_ia64` to detect the `mga` program, end exit with an error if that doesn't exist:
https://github.com/simroux/VirSorter/blob/c9b8943466cdd9914fc0eddf7be40d3caa2bb92f/Scripts/Step_first_add_custom_phage_sequence.pl#L42
https://github.com/simroux/VirSorter/blob/c9b8943466cdd9914fc0eddf7be40d3caa2bb92f/Scripts/Step_1_contigs_cleaning_and_gene_prediction.pl#L25
Since the name of the executable is `mga_osx` on OSX platforms, those commands won't work.

I would suggest to change the README to point to the [conda package](https://anaconda.org/bioconda/metagene_annotator) for MetaGeneAnnotator, which provides the `mga` command, then call `which mga` in the two scripts above.
For the manual installation, you could change the `ln` command to create a `mga` symlink instead of `mga_linux_ia64`.

I hope you will find this comment useful, and thanks again for your work.

Simone

**Comment by simroux** [comment]
Thanks for reporting this ! We need to keep the "mga_linux_ia64" for compatibility with older docker containers, but I added the possibility to also look for "mga" executables (i.e. which would have been installed through conda).

**Comment by simone-pignotti** [comment]
Hi Simon,

That works as well, I just tested it on OSX with bioconda's `mga`. Thanks a lot for the quick fix!

Simone
