### ISSUE TITLE
Encode.c error

### ISSUE THREAD

**Issue by YiweiZhu** [simroux/VirSorter#38]
I am installing VirSorter in bioconda following your commands. But then I iniciate wrapper_phage_contigs_sorter_iPlant.pl, I get 
"Encode.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)". 
It is Encode.c, not Listuntil.c. I create the two shell files in activate.d and deactivate.d folder as you recommended, but it doesn't work.

**Comment by simroux** [comment]
Encode.c and Listuntil.c errors typically come from the same issue, which should be solved by the two shell files in activate.d and deactivate.d.

If you start a new terminal, load the conda environment, and try ">env | grep PERL": what result do you get ?

**Comment by YiweiZhu** [comment]
Thanks @simroux ! I restart the terminal. The command can run now.

**Comment by simroux** [comment]
Great ! :-)
