### ISSUE TITLE
Excessively large 'err' log file when running with custom phage db (--cp flag)

### ISSUE THREAD

**Issue by mshamash** [simroux/VirSorter#44]
Hello,

When running a set of contigs with a --cp flag, the 'err' log file in "logs" folder of working directory ends up being huge (200-400 MB each time), compared to when I run without the --cp flag, it is only a few kb.

The contents of the large 'err' log file is the same line over and over, almost 2 million times:

`Use of uninitialized value in concatenation (.) or string at /home/ubuntu/anaconda3/envs/virsorter/lib/site_perl/5.26.2/Bio/SeqUtils.pm line 375.`

(/home/ubuntu/anaconda3/ is the path to my anaconda3 installation)

I'm not sure if this is a bug, or if it can be fixed easily, since it takes up a large amount of space when trying to download in bulk all of the output folders from VirSorter. If not, I can try and exclude this folder from downloads, just thought I would bring it up nonetheless.

Best,

Michael

**Comment by simroux** [comment]
Hi Michael,

This is not a "real" bug, but it is annoying. It's relatively easy to fix, we need to add an "id" to the BioSeq object in the script "Step_first_add_custom_phage_sequence.pl" (l. 163). I just updated the scripts on github, but if you already have a custom install you should be able to adjust the scripts on your side.

Best,
Simon

**Comment by mshamash** [comment]
Hi Simon,

Thanks for the fix. I will update my scripts locally. 

Best,
Michael
