### ISSUE TITLE
Step 1.3 error

### ISSUE THREAD

**Issue by DNADoubleFelix** [simroux/VirSorter#53]
I just installed Virsorter on a new machine. Whenever I try to run it (on a file that worked before, a couple months ago) I get this error after step 1.3:

No file output/Pa_PAO1_107/r_0/Contigs_prots_vs_New_unclustered.tab, nothing new to add to output/Pa_PAO1_107/Contigs_prots_vs_Phage_Gene_unclustered.tab

I am using the following command : 
`wrapper_phage_contigs_sorter_iPlant.pl -f test/Pa_PAO1_107.fna --db 1 --wdir output/Pa_PAO1_107 --ncpu 4 --data-dir virsorter-data`

`Bin            : /home/felix/miniconda2/envs/virsorter/bin`
`Dataset        : VIRSorter`
`Input file     : test/Pa_PAO1_107.fna`
`Db             : 1`
`Working dir    : output/Pa_PAO1_107`
`Custom phages  : `
`Data dir       : virsorter-data`
`Num CPUs       : 4`
`blastp         : blastp`

I have attached my log files here. I made sure all my dependencies were installed correctly, I'm going through the conda environment. Do you have any idea what's happening? Let me know if I can give you more information.

Thanks for any help!

[err.txt](https://github.com/simroux/VirSorter/files/3673753/err.txt)
[out.txt](https://github.com/simroux/VirSorter/files/3673754/out.txt)

**Comment by simroux** [comment]
Hmm this is weird, and may related to one of the errors in https://github.com/simroux/VirSorter/issues/52.

Would it be possible for you to bundle the whole output directory as a tar.gz or a zip and send it to me ? Unfortunately, the logs alone just complain about a blast file missing but don't say why this blast (apparently) failed :-/

**Comment by genomics-pixel** [comment]
Dear Simon and DNADoubleFelix,

Sorry to interrupt your conversation.

I noticed that my issue was referenced and wanted to let you know
that I was using the "--diamond" to run my analyses.

Sincerely,
Hiroki Nishiyama
