### ISSUE TITLE
empty results because mga_linux_ia64 could not been executed

### ISSUE THREAD

**Issue by bognabognabogna** [simroux/VirSorter#59]
Hi, 
while runnng VirSorter I get the following error:
sh: ~/opt/miniconda3/envs/virsorter/bin/mga_linux_ia64: cannot execute binary file

Is that because I run it on macOSX?
Or is there a way to fix it?

Best
Bogna

**Comment by simroux** [comment]
Hi,

It does seem like there is an issue with the way mga was installed. Did you try to install it through your conda environment ? If so, it seems like conda installed a version of mga that is compiled for linux, not for maxOSX (as best as I can tell). I would suggest removing mga from the conda environment, and instead install the mac version separately (from http://metagene.nig.ac.jp/metagene/download_mga.html).

Best,
Simon

**Comment by bognabognabogna** [comment]
Thank you Simon!
Yes,  I am in the conda environment. But to be honest I am not sure which conda folder I should use to install mga manually?
I have also found VirSorter on the cyverse platform and I managed to run it there.
Is the version on the platform very different to the one here?

**Comment by simroux** [comment]
The VirSorter app on the CyVerse platform is not very different (at all) to the one here, so if you managed to make it work there, you can safely use the results obtained !
