### ISSUE TITLE
An error from virsorter of cyverse

### ISSUE THREAD

**Issue by minsookim1983** [simroux/VirSorter#6]
Hello,

I am trying to do virsorter on my data on Cyverse, but I got an error message only. My input file is contigs.fasta file (~500Mb) from metagenomic sequences. I presume that complex header of each sequence makes it wrong. Here is the log_out and log_err files attached. 
[err.txt](https://github.com/simroux/VirSorter/files/515090/err.txt)
[out.txt](https://github.com/simroux/VirSorter/files/515091/out.txt)
I hope you to check what is wrong with me. Thank you.

Min-Soo

**Comment by simroux** [comment]
Hi Min-Soo,

This seems more like a CyVerse question that a VirSorter question, so I suggest you to submit your question and provide the log files to http://ask.iplantcollaborative.org/questions/

Best,

Simon
