### ISSUE TITLE
Step1 failed.!

### ISSUE THREAD

**Issue by Vishu1511** [simroux/VirSorter#63]
While working on the tool, I got this error of 

> Step 1 failed, we stop there: either /home/lab202/VISHAL/TOOLS/VirSorter/output/fasta/VIRSorter_prots.fasta or /home/lab202/VISHAL/TOOLS/VirSorter/output/fasta/VIRSorter_nett_filtered.fasta were not found

I have followed the conda installation protocol, where I just skipped the sym ink step as i wanted it to run with the whole command. I am using a fasta file.

The command which I used is:
`perl wrapper_phage_contigs_sorter_iPlant.pl --fna file.fna`

Please can anyone help me with the  issue, as I am unable to know what is the error done by me.!

**Comment by Vishu1511** [comment]
Okay just now while reading about similar issues in issue section I read about running the scrip Step1 separately, I tried running that,
But always getting error as :

> Can't locate Bio/Seq.pm in @INC (you may need to install the Bio::Seq module) (@INC contains: /home/lab202/miniconda3/envs/virsorter/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/lab202/miniconda3/envs/virsorter/lib/site_perl/5.26.2 /home/lab202/miniconda3/envs/virsorter/lib/5.26.2/x86_64-linux-thread-multi /home/lab202/miniconda3/envs/virsorter/lib/5.26.2 .) at Step_1_contigs_cleaning_and_gene_prediction.pl line 5.
BEGIN failed--compilation aborted at Step_1_contigs_cleaning_and_gene_prediction.pl line 5.

I tried installing the perl module through cpan (ofcourse) **Bio::Seq** but it doesn't seem to work even after that.

Please is there anyway anyone can help me, as I have been trying to run this tool since 3 days.

**Comment by simroux** [comment]
Hi,
This looks like an issue with the conda installation (Bio::Seq should have been installed via Conda, but it seems like Perl doesn't find it). Could you try the fix we suggest in the Readme (https://github.com/simroux/VirSorter#note-for-conda-installation) so that perl can "see" the conda-installed libraries correctly, and then try to run Step_1 again ?

**Comment by Vishu1511** [comment]
Thank you so much for the help and reply, but even after following the steps, while running the Step_1 script I am getting the same error, do I need to install the Bio::Seq using cpan again.?

**Comment by simroux** [comment]
No, you shouldn't have to install anything with cpan.

Can you list the packages installed in your conda environment using conda list (https://docs.conda.io/projects/conda/en/latest/commands/list.html), and paste the results here ?

**Comment by Vishu1511** [comment]
[package-list.txt](https://github.com/simroux/VirSorter/files/4196545/package-list.txt)
Yes, here is the list of packages I have in the conda environment.

Thank you for your time and help.

**Comment by Vishu1511** [comment]
In addition to this, the Step_5_get_phage_fasta-gb.pl is asking for perl module bio::SeqIO and Step_first_add_custom_phage_sequence.pl is showing same error to that of the Step_1

**Comment by simroux** [comment]
Yes, clearly perl doesn't find the modules installed with conda, so it won't work with Step 5 or Step first either.  It looks like the expected modules are in your conda environment, so we need to figure out why.

Can you share the command lines you use to load the conda environment and then run VirSorter ? Can you also share the results of ">echo $PERL5LIB" ?

**Comment by Vishu1511** [comment]
Yes, the command line which i run in, 
**Load conda environment**
`conda activate virsorter`

**virsorter command**
`wrapper_phage_contigs_sorter_iPlant.pl -f ../F_V_0_29_R.contigs.genes.faa --data-dir ../virsorter-data --wdir output001`

**Command for running single script**
`perl Step_1_contigs_cleaning_and_gene_prediction.pl`
(I have not created the symbolic link for single scripts, that's why using **perl** for running )

and sorry I did not understand what you have asked here.
">echo $PERL5LIB"

**Comment by simroux** [comment]
Sorry, if you enter "echo $PERL5LIB" in a terminal, could you paste the result here ? 
Also, I guess another question is which type of operating system are you working in. Is this a Linux ? Mac ?

**Comment by Vishu1511** [comment]
Oh I am sorry that I did not mention, I am working on a Linux Centos-7 (os) 

and I did not get anything but a blank after I enter the command `echo $PERL5LIB`

**Comment by simroux** [comment]
Hmmm that's weird. Is this after running "conda activate virsorter" ? And could you try "echo PERL5LIB" (i.e. without the $ sign) ?

**Comment by Vishu1511** [comment]
No, this is wihtout running "Conda activate virsorter" and,
I yes I got this 

> PERL5LIB

after running that command without $ sign

**Comment by simroux** [comment]
Ok, so let's run this within the conda environment, i.e.:
> conda activate virsorter
> echo $PERL5LIB

**Comment by Vishu1511** [comment]
Now, inside the environment, running the command without "$" sign I am getting the same result i.e., **PERL5LIB** and runnning it with the "$", there is no result/output.

**Comment by simroux** [comment]
This is weird, something is probably wrong with the way your conda environment is setup, and it's likely not a VirSorter issue.
Looking into other issue with perl modules in conda environment (e.g. https://github.com/BioContainers/containers/issues/84), it looks like one way to fix it is to run something like:
>export PERL5LIB="/opt/conda/lib/perl5/site_perl/5.22.0"

Where you replace "/opt/conda/lib/perl5/site_perl/5.22.0" by the path to the perl libraries in your conda folder

**Comment by Vishu1511** [comment]
Okay thank you so much for your time and help, I will check this and let you know the progress.

**Comment by Vishu1511** [comment]
Okay after running the `export PERL5LIB="/opt/conda/lib/perl5/site_perl/5.22.0"` command I got the result as 

> /home/lab202/miniconda3/lib/site_perl/5.26.2/

So, know may I use the tool.?

I am sorry I may sound lame, bare me because I am new to bioinformatics, with little to no much knowledge about programming.

**Comment by simroux** [comment]
Yes, you should try again, and see if it works now :-)

**Comment by Vishu1511** [comment]
I am sorry sir I am getting the same error as earlier.

**Comment by simroux** [comment]
Then I'm sorry, it's beyond my comprehension. From my point of view, it
looks like there is an issue with conda: you installed the bioperl package,
but perl don't see them.

Any chance you could run your analdys on CyVerse (https://de.cyverse.org/de/)
? That would let you run virsorter without the need to install it locally

**Comment by Vishu1511** [comment]
Yes, I am doing so Sir, Thank you So much for the help and time.
