### ISSUE TITLE
Fix "query" in Step_first_add_custom_phage_sequence.pl

### ISSUE THREAD

**Issue by brymerr921** [simroux/VirSorter#7]
Line 222 says "my $cmd_blast="$path_to_blastp -queury $prot_file_to_cluster -db $db -out $out_blast -outfmt 6 -num_threads 10 -evalue 0.00001"; # On 10 cores to keep a few alive for the rest of the scripts" and it's causing BLAST to throw an error
Error: Unknown argument: "queury".  (Change queury to query)

Also, both of these lines should have (I assume) -dbtype prot added to them (shown in bold).
line 212: my $cmd_format="$path_to_makeblastdb -in $prot_file_to_cluster -out $db **-dbtype prot**";
line 324: $out=\`$path_to_makeblastdb -in $final_pool_unclustered -out $final_blastable_unclustered **-dbtype prot**\`;

**Comment by simroux** [comment]
Good catch, this is now fixed (in the github version). Thanks for notifying us !

**Comment by brymerr921** [comment]
I kept getting an error while trying to run VirSorter if I didn't add -dbtype prot at the specified locations. Is this just me or is it supposed to be in the code?

line 212: my $cmd_format="$path_to_makeblastdb -in $prot_file_to_cluster -out $db -dbtype prot";
line 324: $out=`$path_to_makeblastdb -in $final_pool_unclustered -out $final_blastable_unclustered -dbtype prot`;
