### ISSUE TITLE
Getting 500 Error from Zenodo data repo?

### ISSUE THREAD

**Issue by maximilianpress** [simroux/VirSorter#73]
Hi, I was trying to download the v2 data as follows but I am getting an error that seems to be Zenodo-specific:

```
wget https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz
Resolving zenodo.org (zenodo.org)... 188.184.117.155
Connecting to zenodo.org (zenodo.org)|188.184.117.155|:443... connected.
HTTP request sent, awaiting response... 500 INTERNAL SERVER ERROR
2020-05-29 21:03:21 ERROR 500: INTERNAL SERVER ERROR.
```

I get this running the command either from my laptop or from an AWS instance. 

When I try to navigate to the repo in a web browser I also get a 500 error. Not sure what is up or whether you can do anything about it, but I thought I'd raise it. 

**Is there another source for downloading the data in the meantime?**

Thanks, Max

**Comment by simroux** [comment]
That's weird.. never had this yez with Zenodo. I just put up the file on our FTP while waiting for Zenodo to be fixed: https://portal.nersc.gov/dna/microbial/prokpubs/VirSorter_mirror/virsorter-data-v2.tar.gz 
Let me know if you have any issue with e.g. permissions.
Best,
Simon

**Comment by maximilianpress** [comment]
That link works for wget, thanks very much!

Still getting Zenodo error. I hope it is just me? It would seem bad for Zenodo to be down.

**Comment by maximilianpress** [comment]
The Zenodo wget command is now working for me. Not sure what the issue was? But I will close the issue now.
