### ISSUE TITLE
TypeError: reduction operation 'argmax' not allowed for this dtype

### ISSUE THREAD

**Issue by neptuneyt** [simroux/VirSorter#77]
Hi Simroux,
I would appreciate the VirSorter you contributed to the viral study.
I installed VirSorter via conda and downloaded the database, and version was 2.0.alpha. It returned "TypeError: reduction operation 'argmax' not allowed for this dtype" in the "log/iter-0/step3-classify/classify-merged.log",
![image](https://user-images.githubusercontent.com/39893798/88515260-00d86780-d01e-11ea-92ee-e14fd5bb3747.png)
  when  I run a test viral sequence(see test.fa) with above command
```
virsorter run -i test.fa -j 100 -w virsorter_classification/; } &>virsorter.log&
```  
test.fa
```
>NC_001798.2 Human herpesvirus 2 strain HG52, complete genome
AGTCCCCGTCTTGCCGCGCGGGGGCGGGCGCGGGAAAAAAGCCGCGCGGGGGCGCCCGCGGGAAGGCAGCCCCGCGGCGC
GCGGGGGGAGGGGCGGCGCCCGCGGGGGAGCGGCCGGCTCCGGGGGAGGGACGGGGAAGGGGGCGCGCGGGGCTGCCCTG
CCGCCCGCCCGCCGCCGCCGCCCGCCTTCGCGCCCCCCCCCAAAAAACACCCCCCCCGGGGGTTGACTCCCCGGGGGAAA
AGAGGCGGGGCGGGAGTCCCCGTCCTGCCGCCGCCCCTTAAGAGGGCCCGCAACACGGCCCGGGCTGCGCACGCCAGCCG
GGACGGGTGAGTTCGCTAGGCAAGCACGGACTGGCGGTTACACGTGCATGCGTGCCGAGTGAACTCTCCCGCCCCGACGC
GCTCCGGCTCCGGGCCTACGCCGAGCCCAGCCGCCCGCCATGTCCCGCCGCCGGGGTCCCCGCCGCCGGGGTCCCCGGCG
CCGGCCGCGCCCCGGCGCTCCAGCCGTGCCGCGCCCCGGCGCTCCAGCCGTGCCGCGCCCCGGCGCGCTCCCAACCGCAG
ACTCCCAAATGGTCCCTGCGTACGACTCGGGAACCGCGGTCGAGAGCGCGCCGGCCGCGTCCTCGCTCCTGCGGCGCTGG
CTGCTGGTGCCCCAGGCGGACGACAGCGACGACGCGGACTACGCCGGCAACGACGACGCAGAGTGGGCGAACAGCCCCCC
GAGCGAGGGCGGGGGGAAGGCGCCGGAGGCCCCGCACGCCGCGCCTGCCGCCGCCTGCCCCCCGCCGCCGCCGCGCAAGG
AGCGCGGGCCGCAGCGCCCCCTTCCGCCCCACCTGGCGCTACGGCTGCGCACCACGACGGAGTACCTGGCGCGCCTGAGC
CTGCGCCGGCGGCGGCCCCCCGCGTCCCCGCCCGCGGACGCGCCGCGCGGGAAGGTACGCCTCCCCTCCGACCCCCTGAC
GCCCCTCCGACCCCCTGACGCCCCTCCGACCCCCTGACGCCCCTCCGACCCCCTGACGCCCCTCCGACCCCCTGACGCCC
CTCCGACCCCCTGACGCCCCTCCGACCCCCGTGTCTCCCCGCCCGCAGGTGTGCTTCTCGCCGCGCGTGCAGGTGCGCCA
...
```

**Comment by simroux** [comment]
Hi,

VirSorter 1 (this repo) is not available via conda. You're trying to install VirSorter 2 (https://github.com/jiarong/VirSorter2), which is still in alpha version, and for which bugs like the one you mention here are still being worked out. From what I can see here, this looks like an issue with some pandas version, but please feel free to fill in an issue on the VirSorter 2 repo, so that Jiarong knows about it and can address it.

Best,
Simon
