### ISSUE TITLE
VIRSorter_phage-signal.csv and VIRSorter_affi-contigs.csv missing, with no predicted viral sequences

### ISSUE THREAD

**Issue by Handymanalan** [simroux/VirSorter#81]
Hi Simon,

I have installed VirSorter but I am getting this error when running:

`/srv/scratch/z3336178/anaconda/envs/virsorter/bin/blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Can't open '/srv/scratch/z3336178/NovaSeq/VirSorter2/Prophages/2017_VS/Test/bin.168.contigs_Out/Contigs_prots_vs_Phage_Gene_unclustered.tab' for reading: 'No such file or directory' at /srv/scratch/z3336178/anaconda/envs/virsorter/bin/Scripts/Step_2_merge_contigs_annotation.pl line 79
Can't open '/srv/scratch/z3336178/NovaSeq/VirSorter2/Prophages/2017_VS/Test/bin.168.contigs_Out/VIRSorter_affi-contigs.csv' for reading: 'No such file or directory' at /srv/scratch/z3336178/anaconda/envs/virsorter/bin/Scripts/Step_3_highlight_phage_signal.pl line 64
Can't open '/srv/scratch/z3336178/NovaSeq/VirSorter2/Prophages/2017_VS/Test/bin.168.contigs_Out/VIRSorter_phage-signal.csv' for reading: 'No such file or directory' at /srv/scratch/z3336178/anaconda/envs/virsorter/bin/Scripts/Step_4_summarize_phage_signal.pl line 84
`

I ran it with this loop command:
`for file in *.fa; do tag=${file%.fa}; wrapper_phage_contigs_sorter_iPlant.pl -f "$tag".fa --no_c --db 1 --wdir /srv/scratch/z3336178/NovaSeq/VirSorter2/Prophages/2017_VS/Test/"$tag"_Out --ncpu 8 --data-dir /srv/scratch/z3336178/VirSorterDatabase/virsorter-data; done`

The resulting VIRSorter_global-phage-signal.csv is empty and there are no predicted viral sequences. As I see VIRSorter_affi-contigs.csv and VIRSorter_phage-signal.csv are missing too.

I have tried your solution by installing openssl (conda install -c anaconda openssl) from issue #39 but it didn't work too.

Attached are my log and error reports if you need them.
[out.txt](https://github.com/simroux/VirSorter/files/5570042/out.txt)
[err.txt](https://github.com/simroux/VirSorter/files/5570043/err.txt)

Thanks!

Cheers

Alan

**Comment by simroux** [comment]
Right, it seems similar to issue #39, which goes beyond VirSorter unfortunately :-( 
Any better luck with the "--diamond" option, which uses diamond instead of blastp ?

**Comment by Handymanalan** [comment]
Thanks I will try that and let you know

**Comment by Handymanalan** [comment]
Sorry for the late reply but the "--diamond" option works!

Cheers

Alan
