### ISSUE TITLE
Split a large fasta file

### ISSUE THREAD

**Issue by chenyj8** [simroux/VirSorter#83]
Hi,

Thank you for this excellent tool!

I have a large fasta file (assembly) and I would like to run the VirSorter. Does it make sense if I split the fasta file to multiple files and run the VirSorter seperately for them? The reason why I am doing this is that it would take a while to run a large fasta file with VirSorter.

Yongjian

**Comment by simroux** [comment]
Hi,

There is no issue with splitting large input fasta files to run VirSorter separately on each of them, and it's actually the recommended approach to optimize compute time.

Best,
Simon
