### ISSUE TITLE
error  during virsorter2 run

### ISSUE THREAD

**Issue by javadgh6** [simroux/VirSorter#85]
I face the following error
any idea?
Error in rule remove_partial_gene:
    jobid: 123
    output: iter-0/pp-circular-flt.gff, iter-0/pp-circular-flt.faa
    conda-env: /home/*****/tools/virsorter2_database/conda_envs/da9264f7
    shell:
        
        Log=/home/****(*/camel-data/camel-megahit-out/virsorter_out/virsorter2.8kb_out/log/iter-0/step1-pp/circular-remove-partial-gene-common.log
        if [ circular = "circular" ]; then
            python /home/*****tools/anaconda2/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/circular-remove-partial-gene.py iter-0/pp-circular.gff iter-0/pp-circular-flt.gff &> $Log || { echo "See error detail in $Log" | python /home/*****/tools/anaconda2/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
            python /home/*****/tools/anaconda2/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/filter-seqs-by-gff.py iter-0/pp-circular-flt.gff iter-0/pp-circular.faa iter-0/pp-circular-flt.faa
        else
            (cd iter-0 && ln -s pp-circular.gff pp-circular-flt.gff)
            (cd iter-0 && ln -s pp-circular.faa pp-circular-flt.faa)
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

**Comment by simroux** [comment]
Hi,

This repo is for VriSorter1, please report VirSorter2 issues/bugs at https://github.com/jiarong/VirSorter2

Thanks,
Simon
