### ISSUE TITLE
Run termination

### ISSUE THREAD

**Issue by 18AS** [simroux/VirSorter#87]
I am getting this error report while trying to run virsorter2 after installation, database downloading and configuring. What is the issue?

CreateCondaEnvironmentException:
Could not create conda environment from /home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/mamba/mamba_env.py", line 43, in mamba_install
        pool, tuple(ordered_channels_dict.keys()), repos, prepend=False
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/mamba/utils.py", line 99, in load_channels
        use_cache=use_cache,
      File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/mamba/utils.py", line 74, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (35) SSL connect error [https://conda.anaconda.org/bioconda/noarch/repodata.json]
    OpenSSL SSL_connect: Connection reset by peer in connection to conda.anaconda.org:443

`$ /home/others/bioinfo/anaconda2/envs/VS/bin/mamba create --quiet --file /home/others/bioinfo/AGPS/db/conda_envs/999c0136.yaml --prefix /home/others/bioinfo/AGPS/db/conda_envs/999c0136`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=VS
                CONDA_EXE=/home/others/bioinfo/anaconda2/bin/conda
             CONDA_PREFIX=/home/others/bioinfo/anaconda2/envs/VS
           CONDA_PREFIX_1=/home/others/bioinfo/anaconda2
    CONDA_PROMPT_MODIFIER=(VS)
         CONDA_PYTHON_EXE=/home/others/bioinfo/anaconda2/bin/python
               CONDA_ROOT=/home/others/bioinfo/anaconda2/envs/VS
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/usr/local/qiime191:/usr/local/qiime191/bin:/usr/local/qiime191/lib:/u
                          sr/local/qiime191/include:/home/others/bioinfo/anaconda2/envs/VS/bin:/
                          home/others/bioinfo/anaconda2/condabin:/usr/local/bin:/usr/bin:/usr/lo
                          cal/sbin:/usr/sbin:/home/others/bioinfo/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/others/bioinfo/anaconda2/envs/VS
            shell level : 2
       user config file : /home/others/bioinfo/.condarc
 populated config files : /home/others/bioinfo/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.6.13.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/others/bioinfo/anaconda2/envs/VS  (writable)
           channel URLs : https://conda.anaconda.org/smaegol/linux-64
                          https://conda.anaconda.org/smaegol/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/au-eoed/linux-64
                          https://conda.anaconda.org/au-eoed/noarch
                          https://conda.anaconda.org/biobakery/linux-64
                          https://conda.anaconda.org/biobakery/noarch
          package cache : /home/others/bioinfo/anaconda2/envs/VS/pkgs
                          /home/others/bioinfo/.conda/pkgs
       envs directories : /home/others/bioinfo/anaconda2/envs/VS/envs
                          /home/others/bioinfo/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.6.13 Linux/3.10.0-1127.13.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 52086:8001
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

  File "/home/others/bioinfo/anaconda2/envs/VS/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 352, in create

**Comment by simroux** [comment]
Hi,

For VirSorter 2 errors, please file an issue in the VirSorter 2 github repo: https://github.com/jiarong/VirSorter2

That being said, the error you get seems to be a Conda error, hopefully it was a temporary one on (one of) the conda server, and it may be solved already ?

Best,
Simon
