### ISSUE TITLE
Cannot execute wrapper..

### ISSUE THREAD

**Issue by franztastic** [simroux/VirSorter#88]

**Comment by franztastic** [comment]
Hello, I am trying to use virsorter but I am struggling to make it work... I don't know where should I place my input file but it seems it cannot be opened...  I've pasted the output and the error...

Many thanks! 

**(virsorter) lauratriginer@MacBook-Pro-Laura-Triginer ~ % wrapper_phage_contigs_sorter_iPlant.pl -f AV_subsampled_5kb_contigs.fa \
                                       --db 1 \
                                       --data-dir ~/virsorter-data**


Bin            : /Users/lauratriginer/miniconda3/envs/virsorter/bin
Dataset        : VIRSorter
Input file     : AV_subsampled_5kb_contigs.fa
Db             : 1
Working dir    : /Users/lauratriginer/virsorter-out
Custom phages  : 
Data dir       : /Users/lauratriginer/virsorter-data
Num CPUs       : 4
blastp         : blastp

Can't open 'AV_subsampled_5kb_contigs.fa' for reading: 'No such file or directory' at /Users/lauratriginer/miniconda3/envs/virsorter/bin/wrapper_phage_contigs_sorter_iPlant.pl line 203

**Comment by simroux** [comment]
Hi ! 

So ideally AV_subsampled_5kb_contigs.fa should be in the same folder as the one you are running wrapper_phage_contigs_sorter_iPlant.pl from. However, I would probably recommend against running VirSorter through the command line altogether unless you have a lot (thousands) of datasets to process. Instead, we have VirSorter easily and freely available on Cyverse: https://de.cyverse.org/. There is also a protocol to run VirSorter on CyVerse: https://www.protocols.io/view/Identifying-Viral-Sequences-Using-VirSorter-Cyvers-eyjbfun. 

And finally even better: we now have VirSorter2 which significantly improved over VirSorter, and also available on CyVerse: https://de.cyverse.org/apps/agave/VirSorter2-2.1.0u2/launch

Hope this helps ! 

Best,
Simon

**Comment by franztastic** [comment]
Thank you very much for your answer! 
I have been able to do it on cyVerse! 

I  need, however to make it work in my computer... finally I made it work but there's an error output and I think that's because my virsorter-data is not well located...
where should it be placed? 

thank you very much and so sorry for that many questions... 

all the best, 

Laura

Error: File existence/permissions problem in trying to open HMM file /data/PFAM_27/Pfam-A.hmm.
HMM file /data/PFAM_27/Pfam-A.hmm not found (nor an .h3m binary of it)


Error: File existence/permissions problem in trying to open HMM file /data/PFAM_27/Pfam-B.hmm.
HMM file /data/PFAM_27/Pfam-B.hmm not found (nor an .h3m binary of it)

BLAST Database error: No alias or index file found for protein database [/Users/lauratriginer/VirSorter/virsorter-out/r_0/db/Pool_new_unclustered] in search path [/Users/lauratriginer/VirSorter::]
Can't open '/Users/lauratriginer/VirSorter/virsorter-out/Contigs_prots_vs_Phage_Gene_Catalog.tab' for reading: 'No such file or directory' at /Users/lauratriginer/miniconda3/envs/virsorter/bin/Scripts/Step_2_merge_contigs_annotation.pl line 103
Can't open '/Users/lauratriginer/VirSorter/virsorter-out/VIRSorter_affi-contigs.csv' for reading: 'No such file or directory' at /Users/lauratriginer/miniconda3/envs/virsorter/bin/Scripts/Step_3_highlight_phage_signal.pl line 64
Can't open '/Users/lauratriginer/VirSorter/virsorter-out/VIRSorter_phage-signal.csv' for reading: 'No such file or directory' at /Users/lauratriginer/miniconda3/envs/virsorter/bin/Scripts/Step_4_summarize_phage_signal.pl line 84

**Comment by simroux** [comment]
So if you are still using the same command line, i.e. "wrapper_phage_contigs_sorter_iPlant.pl -f AV_subsampled_5kb_contigs.fa --db 1 --data-dir ~/virsorter-data", then VirSorter expects the database files to be in "~/virsorter-data/". The steps to download the database would be:

```
cd ~
wget https://zenodo.org/record/1168727/files/virsorter-data-v2.tar.gz
md5sum virsorter-data-v2.tar.gz
# md5sum should return dd12af7d13da0a85df0a9106e9346b45
tar -xvzf virsorter-data-v2.tar.gz
```

I would still recommend using VirSorter2 however .. :-)

**Comment by franztastic** [comment]
THANKS A LOT!! IT WORKS NOW, database was not placed in the correct location... (i'm soooo new)..

I will use VirSorter2 aswell :)

Have a nice day and thank you very much for helping me
