### ISSUE TITLE
I got an error message from virsorter of dockerhub

### ISSUE THREAD

**Issue by minsookim1983** [simroux/VirSorter#9]
Hello,
### Revision 1

Out : 
/usr/local/bin/Scripts/Step_0_make_new_clusters.pl r_1 /wdir/fasta/VIRSorter_prots.fasta r_0/db/Pool_unclustered.faa VIRSorter_new_prot_list.csv >> /wdir/log_out 2>> /wdir/log_err
Step 1.1 new clusters and new database : 
Can't open 'r_1/db/Pool_clusters.hmm' for reading: 'No such file or directory' at 
/usr/local/bin/wrapper_phage_contigs_sorter_iPlant.pl line 292
## rm VIRSorter_new_prot_list.csv ->

I have no idea of why "Pool_clusters.hmm" was not created in r_1/db/. I attached what was seen in my console. [error.txt](https://github.com/simroux/VirSorter/files/524087/error.txt)
Please, let me know what is wrong with me, and what I can do to make it right. Thank you.

Min-Soo

**Comment by simroux** [comment]
Hi Min-Soo,

Unfortunately, this is not an error I've already seen. Could you send me the whole VirSorter output directory (in a zip file),so I can track down which file VirSorter generated and where the potential issue might be ? 

Thanks,

Simon

**Comment by minsookim1983** [comment]
Thank you for your response. I am glad to hear that you have seen before
the problem I have. Here I attached the whole VirSorter output directory
below as a zip file.

One more thing I want to ask is that the sequence containing ambiguous
calls (Ns) is excluded in analysis process? My input file is assembled
contigs, so they contain several Ns in their sequences. I have seen the
message below in log_out file:
"we exclude VIRSorter_bin_357_MFP2_reassmbl_scaffold_16__-gene_41 because
there is a pblm with the sequence -> too many succesive X, F, A, K or P"

Min-Soo
​
 virsorter-specific501.zip
<https://drive.google.com/file/d/0B-02O4J9sOdkRnM3d0djek9PNms/view?usp=drive_web>
​

**Comment by simroux** [comment]
Hi Min-Soo,

I think I got what happened for your initial issue, and this should be fixed now in the github version of the scripts (not yet pushed to the Docker version though). Thanks for notifying us !

For your second questions (contigs with "Ns"), this is not a problem, the only thing is that sometimes ORfs are predicted that span this "N" region, and the corresponding predicted proteins will be absurdly long and low complexity (with stretches of X, F, A, K, or P), which will stall hmmsearch. So we exclude these proteins only (not the contigs) from the hmmsearch computations.

Best,

Simon

**Comment by minsookim1983** [comment]
Thank you for your kind response. It is good to hear you that my issue was helpful. I understood that the fixed version is update only on the github, but it is going to be fixed soon in the Docker version. 

Best,

Min-Soo
